services:
  # 1. Твій Streamlit дашборд (Web Service)
  - type: web
    name: news-analyzer-dashboard
    env: docker
    repo: https://github.com/omixilka22/news_analyzer.git
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    startCommand: streamlit run dashboard/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: news-analyzer-db
          property: connectionString

  # 2. Твій планувальник/скрапер (Background Worker)
  - type: worker
    name: news-analyzer-scheduler
    env: docker
    repo: https://github.com/omixilka22/news_analyzer.git
    plan: free
    dockerfilePath: Dockerfile
    dockerContext: .
    startCommand: python scheduler.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: news-analyzer-db
          property: connectionString
      # Токен для Hugging Face (введеш значення в панелі Render)
      - key: HF_TOKEN
        sync: false